[versions]
activity-compose = "1.7.2"
androidx-test-ext-junit = "1.1.5"
androidx-lifecycle = "2.6.1"
accompanist = "0.30.1"
agp = "8.0.2"

core-ktx = "1.10.1"
compose-bom = "2023.06.01"
coroutines = "1.6.4"
icon-extended = "1.5.0-beta02"

data-store = "1.0.0"

detektGradlePlugin = "1.23.0"
espresso-core = "3.5.1"


google-Truth= "1.1.3"

hilt = "2.45"
dagger-hilt = "2.46.1"
hilt-navigation = "1.0.0"

junit = "4.13.2"

kotlin = "1.8.10"
kotlinter = "3.14.0"
ksp = "1.8.10-1.0.9"


lifecycle-runtime-ktx = "2.6.1"
leakCanary = "2.11"

lottieCompose = "4.0.0"
moshi = "1.15.0"
mock-library = "1.13.4"
material2 = "1.4.3"

navigation = "2.6.0"

retrofit = "2.9.0"
room = "2.5.2"

splashscreen ="1.0.1"

turbine = "0.12.3"

viewmodel = "2.6.1"
window = "1.1.0"
kover ="0.7.2"




[libraries]
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
splashscreen = { group ="androidx.core", name = "core-splashscreen", version.ref="splashscreen"}

androidx-lifecycle = { group ="androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref ="androidx-lifecycle"}
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }


datastorelib = { group ="androidx.datastore" ,name ="datastore-preferences", version.ref ="data-store"}


compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
coroutine-test = { group= "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test",version.ref = "coroutines"}
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektGradlePlugin" }

espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

googleTruth = { group ="com.google.truth", name ="truth", version.ref = "google-Truth" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-nav = { group = "androidx.hilt" , name ="hilt-navigation-compose", version.ref = "hilt-navigation" }

iconextended = {group="androidx.compose.material",name ="material-icons-extended-android", version.ref="icon-extended"}

junit = { group = "junit", name = "junit", version.ref = "junit" }

lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }


material3 = { group = "androidx.compose.material3", name = "material3" }
material2 ={ group =  "androidx.compose.material", name ="material", version.ref = "material2"}
mock-library = { group = "io.mockk", name = "mockk", version.ref = "mock-library"}

navigation-library = { group ="androidx.navigation", name ="navigation-compose", version.ref ="navigation"}

ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

square-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
square-moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
square-moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
square-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
square-retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit"}

turbine = { group = "app.cash.turbine", name = "turbine" , version.ref = "turbine"}

viewmodel-lifecycle = { group ="androidx.lifecycle", name ="lifecycle-viewmodel-compose",version.ref="viewmodel" }


[plugins]

androidApplication = { id = "com.android.application", version = "8.2.0-alpha14" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android",version.ref = "dagger-hilt" }
hiltplugins ={ id = "com.google.dagger.hilt.android" }
detekt = { id = "io.gitlab.arturbosch.detekt",version.ref = "detektGradlePlugin" }
kolinter = { id ="org.jmailen.kotlinter",  version.ref ="kotlinter" }
ksp = { id = "com.google.devtools.ksp" ,  version.ref = "ksp"}
kover = {id="org.jetbrains.kotlinx.kover", version.ref= "kover"}

kapt = { id ="kotlin-kapt" }

[bundles]

